[alias]
run-cli = "run -p cljvindent-cli"
build-cli = "build -p cljvindent-cli --release --bin cljvindent"
build-emacs = "build -p cljvindent-core --release --lib"
test-all = "test --workspace"
check-all = "check --workspace"
